FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_PASTE_API=/api
ARG VITE_AUTH_API=/auth
ARG VITE_FILE_RESOLVE_BASE=/api/resolve
ARG VITE_TOKEN_OWNER_PATH=/api/token-owner
ARG VITE_PUBLIC_SITE_ORIGIN=
ARG VITE_HISTORY_WS=
ARG VITE_ENABLE_SHAREX=1
ARG VITE_ENABLE_AUTH=1
ARG VITE_REPOSITORY_URL=https://github.com/emiliauh/yaemipaste
ARG VITE_MAX_EXPIRY_DAYS=14
ENV VITE_PASTE_API=$VITE_PASTE_API
ENV VITE_AUTH_API=$VITE_AUTH_API
ENV VITE_FILE_RESOLVE_BASE=$VITE_FILE_RESOLVE_BASE
ENV VITE_TOKEN_OWNER_PATH=$VITE_TOKEN_OWNER_PATH
ENV VITE_PUBLIC_SITE_ORIGIN=$VITE_PUBLIC_SITE_ORIGIN
ENV VITE_HISTORY_WS=$VITE_HISTORY_WS
ENV VITE_ENABLE_SHAREX=$VITE_ENABLE_SHAREX
ENV VITE_ENABLE_AUTH=$VITE_ENABLE_AUTH
ENV VITE_REPOSITORY_URL=$VITE_REPOSITORY_URL
ENV VITE_MAX_EXPIRY_DAYS=$VITE_MAX_EXPIRY_DAYS

RUN npm run build

FROM nginx:1.27-alpine
ENV CSP_CONNECT_SRC=""
ENV CSP_TURNSTILE_SRC=""
ENV API_UPSTREAM="http://paste-api:8000"
ENV NGINX_ENVSUBST_FILTER="^(CSP_(CONNECT|TURNSTILE)_SRC|API_UPSTREAM)$"
COPY docker/nginx/default.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
